-keep class com.shortsshield.** { *; }
-keepclassmembers class * extends android.accessibilityservice.AccessibilityService { *; }
-keep class kotlin.** { *; }
-dontwarn kotlin.**
-keepattributes SourceFile,LineNumberTable
