name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # This line tells GitHub the project is inside the 'shortsshield' folder
    defaults:
      run:
        working-directory: ./shortsshield

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShortsShield-App
          # This points to where the file will be created inside your folder
          path: shortsshield/app/build/outputs/apk/debug/*.apk
